### PR TITLE
Remove prohibited tests for and add new tests for A8B8G8R8 formats

### PR DESCRIPTION
**Pull request by MarkCallow**
and golden result files. This is for https://github.com/KhronosGroup/KTX-Software/issues/860 to allow these formats.

@aqnuep should I add tests for ensuring validate and info work with these formats? If so, where?

### CODE REVIEW

**Comment by aqnuep** [comment]
> @aqnuep should I add tests for ensure validate and info work with these formats? If so, where?

Yes, I'd strongly suggest doing that. In general, I think we should have at least some tests for every format that is supposed to be supported.

**Comment by MarkCallow** [comment]
> I think we should have at least some tests for every format that is supposed to be supported.

I don't see any for the previously supported formats which is why I asked "where". I probably missed them.

Please point me at the tool again that you use for creating ktx files for the tests.

**Comment by MarkCallow** [comment]
@aqnuep are you aware there are some invalid ktx2 files under `golden`? I ran `ktx invalidate` over the whole corpus in the `main` branch by way of `find`. I don't know any of the file names. Having an equivalent to grep's `-H` option to print the name of the file when printing validation errors would be very useful when processing so many files. All the newly added files are valid.

**Comment by MarkCallow** [comment]
Please review soon. I want to get this merged.

**Comment by aqnuep** [comment]
> @aqnuep are you aware there are some invalid ktx2 files under golden? I ran ktx invalidate over the whole corpus in the main branch by way of find. I don't know any of the file names. Having an equivalent to grep's -H option to print the name of the file when printing validation errors would be very useful when processing so many files. All the newly added files are valid.

FYI, I looked into these. It seems that these are the result of some minor corner case issues, some of which is just overzealous validation of data layouts. I'll put together a fix for these.

**Pull request merged**
