### PR TITLE
Tests to fix issue 752

### PR DESCRIPTION
**Pull request by aqnuep**
Reference output updates for https://github.com/KhronosGroup/KTX-Software/issues/752.

### CODE REVIEW

**Comment by aqnuep** [comment]
@MarkCallow, please merge this as well, otherwise we don't have the up-to-date CTS in the main branch for https://github.com/KhronosGroup/KTX-Software/pull/753, which you already merged.

In general, you need to merge the CTS changes corresponding to code changes.

**Comment by MarkCallow** [comment]
Sure. Sorry I didn’t think about this before.

Please sign the CLA so I can do the merge.

    -Mark

**Comment by aqnuep** [comment]
That's weird. I had the CLA signed already for Khronos repositories. Anyway, I did it again.

**Comment by MarkCallow** [comment]
> That's weird. I had the CLA signed already for Khronos repositories. Anyway, I did it again.

It seems to be a per repo thing. It is still showing as not signed.

**Comment by aqnuep** [comment]
> It seems to be a per repo thing. It is still showing as not signed.

I see. We had a discussion with @outofcontrol a while back when we similarly saw CLA warnings being shown when downstreaming code from one Khronos repository to another. I guess that confirms that this works on a per repo basis, but I believe it shouldn't, as the CLA itself applies to all Khronos repositories. Maybe this is something that's worth looking into Khronos-wide.

**Comment by aqnuep** [comment]
Btw, I signed it on this repo as well, but apparently the status doesn't update.

**Pull request merged**
